# API LIST

@rootUrl=http://localhost:8000

### Check server Status
GET {{rootUrl}}

### Auth API

POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"satish",
    "lName":"subedi",
    "email":"satish0@gmail.com",
    "phone":"9849679038",
    "password":"Sat@123"
}

### Post to activate User
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionid":"677575cbccfd2c217406174a",
    "t":"31fbe892-1e1f-48fc-86a8-0de421598571"
}

### Post login User
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"satish@gmail.com",
    "password":"sat@123"
}

### Get User Profile
GET  {{rootUrl}}/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdGlzaEBnbWFpbC5jb20iLCJpYXQiOjE3MzUzMTU2MDQsImV4cCI6MTczNTMxNjUwNH0.qW1pKOKBY3Oqv12vrV5djxJqg2aH90HZCRZRxLyljwU


### Get User Profile
GET  {{rootUrl}}/api/v1/auth/renew-jwt
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhdGlzaEBnbWFpbC5jb20iLCJpYXQiOjE3MzU0NTU4NzYsImV4cCI6MTczODA0Nzg3Nn0.oTKNmt3x7k_FOGltTyNLGSc_PrWEASu83qwUit60GlE

### Generate OTP
POST {{rootUrl}}/api/v1/auth/forget-password
Content-Type: application/json

{
    "email":"satish@gmail.com"
    
}

### Reset-Password-user 
POST {{rootUrl}}/api/v1/auth/reset-password
Content-Type: application/json

{
    "email":"satish@gmail.com",
    "password":"Satish@1234",
    "otp":1644
}