# API LIST

@rootUrl=http://localhost:8000

### Check server Status
GET {{rootUrl}}

### Auth API

POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName":"satish",
    "lName":"subedi",
    "email":"satish@gmail.com",
    "phone":"9849679",
    "password":"sat@123"
}

### Post to activate User
POST {{rootUrl}}/api/v1/auth/activate-user
Content-Type: application/json

{
    "sessionid":"6768d8edde3f0a0081a5270e",
    "t":"95ece22d-76e3-442c-84b4-f91d5bd9f642"
}

### Post login User
POST {{rootUrl}}/api/v1/auth/login
Content-Type: application/json

{
    "email":"satish@gmail.com",
    "password":"sat@123"
}